version: "3"
services:
  web:
    build: ./smoke-editor
    volumes:
      - .:/smoke
    working_dir: /smoke/smoke-editor
    entrypoint:
      - sh
      - .travis/test.sh
    tty: true
  backend:
    image: python:3.6
    entrypoint:
      - bash
      - -l
      - test.sh
    volumes:
      - ./smoke-backend:/smoke
    working_dir: /smoke
    tty: true
  smokr:
    image: python:3.6
    entrypoint:
      - bash
      - -l
      - test.sh
    volumes:
      - ./smokr:/smoke
    working_dir: /smoke
    tty: true
