version: "3"
services:
  web:
    image: mhart/alpine-node:latest
    volumes:
      - .:/smoke
    working_dir: /smoke/smoke-editor
    entrypoint:
      - sh
      - .travis/test.sh
    tty: true
  backend:
    image: python:3.7-alpine3.8
    entrypoint:
      - sh
      - test.sh
    volumes:
      - ./smoke-backend:/smoke
    working_dir: /smoke
    tty: true
  smokr:
    image: python:3.7-alpine3.8
    entrypoint:
      - sh
      - test.sh
    volumes:
      - ./smokr:/smoke
    working_dir: /smoke
    tty: true
