version: '3'
services:
  web:
    image: node:8.12-alpine
    entrypoint:
      - sh
      - -l
      - run.sh
    volumes:
      - ./smoke-editor:/smoke
    ports:
      - "8080:8080"
    working_dir: /smoke
    depends_on:
       - backend
    tty: true
  backend:
    image: python:3.7-alpine3.8
    entrypoint:
      - sh
      - -l
      - run.sh
    volumes:
      - ./smoke-backend:/smoke
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    working_dir: /smoke
    tty: true
